### ISSUE TITLE
 Inherited class access to base class properties

### ISSUE THREAD

**Issue by ComradeAlpha** [ExM/NConfiguration#1]
When I  inherite one config class from another if base class properties have private setters, they will not be  initialized by config values.

example:
[DataContract(Name = "Foo")]
class Foo 
{
    public string P1 {get; private set;}
}

[DataContract(Name = "Bar")]
class Bar
{
    public string P2 {get; private set;}
}

**Comment by ExM** [comment]
This deserializer use only public setters.
but I'll include this feature in the next release
